[package]
name = "teleport-ui"
version = "2.1.0"
description = "Teleport Database Proxy UI"
authors = ["Luqi"]
edition = "2021"

[lib]
name = "teleport_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "teleport-ui"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.8"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
